name: Ci

on:
  pull_request:
    branches: ["feature/*"]
  push:
    branches: ["feature/*", trunk]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run format-check
      - run: npm run lint
      - run: npm test
